### ISSUE TITLE
引用 weapp-session，出现语法错误？

### ISSUE THREAD

**Issue by sunsnow8** [CFETeam/weapp-session#2]
下面是什么原因啊

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/release/node-weapp-session-cbb/app.js:18:16)
    at Module._compile (module.js:409:26)

app.js 的18行代码是：var wSession = require('weapp-session');
很奇怪，我注释调第18行代码就没错误了，是什么原因呢

**Comment by sunsnow8** [comment]
我的qq 是17007325，可以加我qq，帮我远程看一下吗，谢谢
